<section>
  <h2>Locul nașterii și originea</h2>
  <p>S-a născut în Sighișoara, în Transilvania, în 1431. Tatăl său, Vlad Dracul, era membru al Ordinului Dragonului. De aici vine și numele de „Drăculea”.</p>
</section>

<section>
  <h2>Domniile lui Vlad Țepeș</h2>
  <ul>
    <li>1448 – Prima domnie, scurtă.</li>
    <li>1456–1462 – Cea mai importantă domnie.</li>
    <li>1476 – A treia domnie, urmată de moarte.</li>
  </ul>
</section>

<section>
  <h2>Luptele și victoriile</h2>
  <p>A luptat împotriva boierilor trădători și a Imperiului Otoman. A folosit tactici de gherilă, pământ pârjolit și atacuri nocturne, obținând victorii notabile.</p>
</section>

<section>
  <h2>Moartea lui Vlad Țepeș</h2>
  <p>A fost ucis în 1476, aproape de București. Se presupune că a fost îngropat la Mănăstirea Snagov.</p>
</section>

<section>
  <h2>Concluzie</h2>
  <p>Vlad Țepeș a fost un simbol al dreptății și un apărător al țării. Moștenirea lui este importantă, chiar dacă a fost mitizată de-a lungul timpului.</p>
</section>
